# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/Syntax-Feature-Qwa/project>
	:perl_version_from _:main ;
	:version_from _:main ;
	:readme_from _:main ;
	:test_requires
		"Test::More 0.61";
	:requires
		"strict",
		"Devel::Declare",
		"Devel::Declare::Context::Simple",
		"B::Hooks::EndOfScope",
		"Sub::Install",
		"namespace::clean".

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/Syntax/Feature/Qwa.pm" .

